import { Controller, Post, Body } from '@nestjs/common';
import { AuthService } from './auth.service';
import { RegisterDto } from './dto/register.dto';
import { VerifyUserDto } from './dto/verifuUser.dto';
import { RedisUtil } from 'src/utils/redis.util';
import { REFRESH_TOKEN } from 'src/constants';

 @Controller('auth')
export class AuthController {
  constructor(
    private readonly authService: AuthService,
    private readonly redisUtil: RedisUtil,
  ) {}

   @Post('register')
  async create(@Body() registerDto: RegisterDto) {
    await this.authService.create(registerDto);

    return 'otp was sent';
  }

  @Post('verifyUser')
  async verifyUser(@Body() verifyUserData: VerifyUserDto) {
    const user = await this.authService.verifyUser(verifyUserData);
    
    const { password, ...rest } = user;

     // MUST tokens must be generated by jwt in utils/jwt.util, they are just examples
    const accessToken = 'hello access';
    const refreshToken = 'hello refresh';
    

    const ttlSeconds = Number(process.env.REFRESH_TOKEN_TIME) * 60 * 60;
    await this.
    redisUtil.setValue(
      `${REFRESH_TOKEN}: ${user.email}`,
      refreshToken,
      ttlSeconds,
    );

    return {
      rest,
      tokens: {
        accessToken,
        refreshToken,
      },
    };
  }
}
